# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_factor <- function(F, L) {
    .Call(`_bpCausal_qr_factor`, F, L)
}

sortX <- function(X, index) {
    .Call(`_bpCausal_sortX`, X, index)
}

getSubX <- function(X, index) {
    .Call(`_bpCausal_getSubX`, X, index)
}

reShape <- function(fit, index, idBreak) {
    .Call(`_bpCausal_reShape`, fit, index, idBreak)
}

breakID <- function(id) {
    .Call(`_bpCausal_breakID`, id)
}

genXY <- function(x, y, idBreak) {
    .Call(`_bpCausal_genXY`, x, y, idBreak)
}

genCov1 <- function(X, invCov0, sigma2) {
    .Call(`_bpCausal_genCov1`, X, invCov0, sigma2)
}

genMu <- function(X, Y, Cov1, sigma2) {
    .Call(`_bpCausal_genMu`, X, Y, Cov1, sigma2)
}

sampleN <- function(X, Y, Cov0, sigma2) {
    .Call(`_bpCausal_sampleN`, X, Y, Cov0, sigma2)
}

sampleCN <- function(M, S, m) {
    .Call(`_bpCausal_sampleCN`, M, S, m)
}

sampleSubAlpha <- function(M, S, r, id) {
    .Call(`_bpCausal_sampleSubAlpha`, M, S, r, id)
}

iterGenAlpha <- function(XX, XY, A0, N, k, r, sigma2) {
    .Call(`_bpCausal_iterGenAlpha`, XX, XY, A0, N, k, r, sigma2)
}

sampleAlpha <- function(X, y, A0, idBreak, N, r, sigma2) {
    .Call(`_bpCausal_sampleAlpha`, X, y, A0, idBreak, N, r, sigma2)
}

genBi <- function(k) {
    .Call(`_bpCausal_genBi`, k)
}

permute <- function(omega, xi) {
    .Call(`_bpCausal_permute`, omega, xi)
}

permuteF <- function(omega, gamma, F) {
    .Call(`_bpCausal_permuteF`, omega, gamma, F)
}

genTildeA <- function(A, gamma, omega, id, r) {
    .Call(`_bpCausal_genTildeA`, A, gamma, omega, id, r)
}

genTildeZ <- function(Z, f, omega, time) {
    .Call(`_bpCausal_genTildeZ`, Z, f, omega, time)
}

genTildeTau <- function(Z, A, Alpha, Xi, Gamma, F, id0, time) {
    .Call(`_bpCausal_genTildeTau`, Z, A, Alpha, Xi, Gamma, F, id0, time)
}

iterGenXi <- function(Xi_old, Phi, XX, XY, T, k, sigma2) {
    .Call(`_bpCausal_iterGenXi`, Xi_old, Phi, XX, XY, T, k, sigma2)
}

sampleXi <- function(X, y, Xi_old, Phi, timeBreak, T, sigma2) {
    .Call(`_bpCausal_sampleXi`, X, y, Xi_old, Phi, timeBreak, T, sigma2)
}

samplePhi <- function(Xi, P0) {
    .Call(`_bpCausal_samplePhi`, Xi, P0)
}

getREfit <- function(X, eff, index) {
    .Call(`_bpCausal_getREfit`, X, eff, index)
}

getFactorFit <- function(gamma, f, index1, index2) {
    .Call(`_bpCausal_getFactorFit`, gamma, f, index1, index2)
}

sampleSigmaE2 <- function(res, c0, d0) {
    .Call(`_bpCausal_sampleSigmaE2`, res, c0, d0)
}

sampleG <- function(a, b) {
    .Call(`_bpCausal_sampleG`, a, b)
}

insertB <- function(B) {
    .Call(`_bpCausal_insertB`, B)
}

rrinvgauss <- function(mu, lambda) {
    .Call(`_bpCausal_rrinvgauss`, mu, lambda)
}

